name: USA - Build and deploy application to ECS

on:
  push:
    branches:
      - production-us

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACTIONS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACTIONS_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: axios/usa-strapi-cms
          IMAGE_TAG: ${{ github.sha }}
          STRAPI_ADMIN_REGION: us
        run: |
          docker build --build-arg STRAPI_ADMIN_REGION=$STRAPI_ADMIN_REGION -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Download dev task definition
        run: |
          aws ecs describe-task-definition --task-definition axios-usa-strapi-cms --query taskDefinition > axios-usa-strapi-cms.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        id: render-container
        with:
          task-definition: axios-usa-strapi-cms.json
          container-name: axios-usa-strapi-cms
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-container.outputs.task-definition }}
          service: axios-usa-strapi-cms-service
          cluster: axios
